version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=product-service  # Name of the database to initialize
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db