version: '4'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # change this to a secure password
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql